version: '3'

services:

  notifier-api:
    image:  sflpro/notifier:snapshot
    ports:
      - "8099:8099"
    depends_on:
      - notifier-worker
    links:
      - db
      - rabbit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notifier
      - SPRING_DATASOURCE_USERNAME=notifier
      - SPRING_DATASOURCE_PASSWORD=notifier
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_FLYWAY_ENABLED=false
      - SPRING_RABBITMQ_HOST=rabbit
      - SPRING_RABBITMQ_USERNAME=notifier
      - SPRING_RABBITMQ_PASSWORD=notifier
      - SPRING_RABBITMQ_PORT=5672
      - NOTIFIER_QUEUE_ENGINE=rabbit
      - SMS_ACCOUNT_SENDER_PHONE=00000000
      - PUSH_NOTIFICATION_PROVIDER=FIREBASE_CLOUD_MESSAGING
      - JAVA_TOOL_OPTIONS="-Dnotification.push.application.arn.test_app.android=test_app -Xmx256m"

  notifier-worker:
    image:  sflpro/notifier-worker:snapshot
    depends_on:
      - db
      - rabbit
      - smtp
    links:
      - db
      - rabbit
      - smtp
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notifier
      - SPRING_DATASOURCE_USERNAME=notifier
      - SPRING_DATASOURCE_PASSWORD=notifier
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_RABBITMQ_HOST=rabbit
      - SPRING_RABBITMQ_USERNAME=notifier
      - SPRING_RABBITMQ_PASSWORD=notifier
      - SPRING_RABBITMQ_PORT=5672
      - NOTIFIER_QUEUE_ENGINE=rabbit
      - FIREBASE_PUSH_ENABLED=true
      - PUSH_NOTIFICATION_PROVIDER=FIREBASE_CLOUD_MESSAGING
      - SMTP_ENABLED=true
      - SMTP_HOST=smtp
      - SMTP_PORT=25
      - SMTP_TIMEOUT=10000
      - SMTP_USERNAME=john
      - SMTP_PASSWORD=secret
      - JAVA_TOOL_OPTIONS="-Dnotification.push.application.arn.test_app.android=test_app -Xmx256m"

  smtp:
    image: namshi/smtp
    environment:
      - SMARTHOST_USER=john
      - SMARTHOST_PASSWORD=secret

  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: notifier
      POSTGRES_PASSWORD: notifier
    ports:
      - "5433:5432"
    volumes:
      - ./../db_init:/docker-entrypoint-initdb.d

  rabbit:
    image: rabbitmq:3.7-management
    hostname: rabbit
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    environment:
        RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
        RABBITMQ_DEFAULT_USER: notifier
        RABBITMQ_DEFAULT_PASS: notifier
        RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15673:15672"
      - "5673:5672"
